Taller/Controllers/CitasController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Taller.Models;
using Taller.Models.Services;
using Taller.Permisos;
using static Taller.Models.CitasModel;

namespace Taller.Controllers
{
    [ValidarPermisos]
    public class CitasController : Controller
    {

        private TallerEntities db = new TallerEntities();
        private CitasService citasService = new CitasService();
        private CarrosService carrosService = new CarrosService();
        // GET: Citas
        public ActionResult Index()
        {
            Usuario usuario = Session["usuario"] as Usuario;
            List<GetCitas_Result> lista = new List<GetCitas_Result>();

            if (usuario != null && usuario.EsAdmin != 1)
            {
                lista = citasService.GetCitas(null, null, usuario.IdUsuario); 
            }
            else if(usuario != null && usuario.EsAdmin == 1)
            {
                lista = citasService.GetCitas(null, null, null);
            }
            return View(lista);
        }

        // GET: Citas/Create
        public ActionResult Create()
        {

            Usuario usuario = Session["usuario"] as Usuario;

            var carros = db.GetCarrosClientes(usuario.IdUsuario).Select(c => new SelectListItem
            {
                Value = c.IdCarroCliente.ToString(), 
                Text = $"{c.Marca} {c.Modelo}" 
            }).ToList();

            var viewModel = new Cita
            {
                Carros = carros,
                FechaInicio = DateTime.Now
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Citas cita)
        {

            GeneralModel resultado = citasService.SetCita(cita);

            if (resultado.Exitoso == 1)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["Mensaje"] = resultado.Mensaje;

                Usuario usuario = Session["usuario"] as Usuario;

                //Obtiene el listado de carros y agrega manejo para poder usarlo en la vista
                var carros = db.GetCarrosClientes(usuario.IdUsuario).Select(c => new SelectListItem
                {
                    Value = c.IdCarroCliente.ToString(), 
                    Text = $"{c.Marca} {c.Modelo}" 
                }).ToList();

                var viewModel = new Cita
                {
                    Carros = carros,
                    FechaInicio = cita.FechaInicio
                };

                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult AprobarRechazar(string idCita, string comentarios, string aprobada)
        {
            Citas cita = new Citas();
            cita.IdCita = Int32.Parse(idCita);
            cita.Comentarios = comentarios;
            cita.Aprobada = Int32.Parse(aprobada);
            cita.FechaInicio = DateTime.Now;
            GeneralModel resultado = citasService.SetCita(cita);

            if (resultado.Exitoso == 1)
            {
                //Retorna json para utilizarlo en el modal de aprobación/rechazo
                return Json(new { success = true });
            }
            else
            {
                //Retorna json para utilizarlo en el modal de aprobación/rechazo
                return Json(new { success = false, mensaje = resultado.Mensaje });
            }
        }

        // GET: Citas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            List<GetCitas_Result> citas = citasService.GetCitas(id, null, null);

            GetCitas_Result cita = citas.FirstOrDefault();

            if (cita == null)
            {
                return HttpNotFound();
            }
            return View(cita);
        }

        // POST: Citas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GeneralModel resultado = citasService.EliminarCita(id);

            if (resultado.Exitoso == 1)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["Mensaje"] = resultado.Mensaje;
                return View();
            }
        }

    }
}

Taller/Views/Citas/Create.cshtml
@model Taller.Models.CitasModel.Cita
@{

    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agendar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Nueva cita</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.IdCarroCliente, "Carro", htmlAttributes: new { @class = "control-label" })
        @Html.DropDownListFor(
            model => model.IdCarroCliente,
            Model.Carros,
            "Seleccionar Carro",
            new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IdCarroCliente, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FechaInicio, "Fecha y Hora de Inicio", htmlAttributes: new { @class = "control-label" })
        <input 
               name="FechaInicio"
               type="datetime-local"
               asp-for="FechaInicio"
               class="form-control"
                   value="@Model.FechaInicio.HasValue ? Model.FechaInicio.Value.ToString("yyyy-MM-ddTHH:mm") : string.Empty" />
        @Html.ValidationMessageFor(model => model.FechaInicio, "", new { @class = "text-danger" })
    </div>


    @if (ViewData["Mensaje"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @ViewData["Mensaje"]
        </div>

    }
<br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-custom-green" id="btnCrear" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Ver listado", "Index")
</div>

Taller/Views/Citas/Delete.cshtml
@model Taller.GetCitas_Result

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar</h2>

<div>
    <h4>¿Estás seguro de que quieres eliminar tu cita?</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Placas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Placas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFin)
        </dd>

        <dt>
            Estatus
        </dt>

        <dd>
            @if (Model.Aprobada == 1)
            {
                <span>Aprobada</span>
            }
            else if (Model.Aprobada == 0)
            {
                <span>Rechazada</span>
            }
            else
            {
                <span>Pendiente</span>
            }
        </dd>

        @if (Model.Comentarios != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Comentarios)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Comentarios)
            </dd>

        }

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-custom-red" /> |
            @Html.ActionLink("Ver listado", "Index")
        </div>
    }
</div>

Taller/Views/Citas/Index.cshtml
@model IEnumerable<Taller.GetCitas_Result>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    Taller.Models.Usuario usuario = Session["Usuario"] as Taller.Models.Usuario;
}

<head>
    <style>
        .estatus-aprobada {
            color: green;
            font-weight: bold;
        }

        .estatus-rechazada {
            color: red;
            font-weight: bold;
        }

        .estatus-pendiente {
            color: orange;
            font-weight: bold;
        }

        .btn-success {
            background-color: green;
            border-color: green;
        }

        .btn-danger {
            background-color: red;
            border-color: red;
        }
    </style>

</head>

<h2>Listado de Citas</h2>
@if (usuario != null && usuario.EsAdmin != 1)
{
    <p>
        @Html.ActionLink("Nueva Cita", "Create")
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Modelo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Placas)
        </th>
        @if (usuario != null && usuario.EsAdmin == 1)
        {
            <th>
                Dueño
            </th>
        }

        <th>
            Estatus
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comentarios)
        </th>
        <th>
            Fecha Inicio
        </th>
        <th>
            Fecha Fin
        </th>
        @if (usuario.EsAdmin != 1)
        {
            <th></th>
        }
        @if (usuario.EsAdmin == 1)
        {
            <th></th>
        }
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Modelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Placas)
            </td>
            @if (usuario != null && usuario.EsAdmin == 1)
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Duenio)
                </td>
            }

            <td>
                @if (item.Aprobada == 1)
                {
                    <span class="estatus-aprobada">Aprobada</span>
                }
                else if (item.Aprobada == 0)
                {
                    <span class="estatus-rechazada">Rechazada</span>
                }
                else
                {
                    <span class="estatus-pendiente">Pendiente</span>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comentarios)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaFin)
            </td>

            @if (usuario.EsAdmin != 1)
            {
                <td>
                    @Html.ActionLink(" Eliminar", "Delete", new { id = item.IdCita })
                </td>
            }
            @if (usuario.EsAdmin == 1 && item.Aprobada == null)
            {
                <td>
                    <a href="javascript:void(0);" onclick="showApproveModal(@item.IdCita, 1)">Aprobar</a> |
                    <a href="javascript:void(0);" onclick="showApproveModal(@item.IdCita, 0)">Rechazar</a>
                </td>
            }
        </tr>
    }

</table>


@*Modal de aprobación/rechazo*@
@Html.AntiForgeryToken()

<div class="modal fade" id="aprobarModal" tabindex="-1" role="dialog" aria-labelledby="aprobarModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="aprobarModalLabel"></h5>
            </div>
            <div class="modal-body">
                <form id="aprobarForm">
                    <div class="form-group">
                        <label for="comentarios">Comentarios</label>
                        <textarea class="form-control" id="comentarios" name="comentarios" rows="3"></textarea>
                        <input type="hidden" id="idCita" name="idCita" />
                        <input type="hidden" id="aprobada" name="aprobada" />
                    </div>
                    <br />
                    <div class="form-group text-right">
                        <button type="button" class="btn" id="btnEnviar">Enviar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
    function showApproveModal(id, aprobada) {
        $('#idCita').val(id);
        $('#aprobada').val(aprobada);
        $('#aprobarModal').modal('show');

        if (aprobada === 1) {
            $('#aprobarModalLabel').text('Aprobar Cita');
            $('#btnEnviar').text('Aprobar').removeClass('btn-danger').addClass('btn-success');
        } else if (aprobada === 0) {
            $('#aprobarModalLabel').text('Rechazar Cita');
            $('#btnEnviar').text('Rechazar').removeClass('btn-success').addClass('btn-danger');
        }

        $('#aprobarModal').modal('show');
    }

    $('#btnEnviar').on('click', function() {
        var idCita = $('#idCita').val();
        var comentarios = $('#comentarios').val();
        var aprobada = $('#aprobada').val();

       $.ajax({
        url: '@Url.Action("AprobarRechazar", "Citas")',
        type: 'POST',
        data: {
            idCita: idCita,
            comentarios: comentarios,
            aprobada: aprobada
        },
           success: function (response) {
               console.log(response.success)
            if (response.success) {
                $('#aprobarModal').modal('hide');
                location.reload(); 
            } else {
                alert('Error al aprobar la cita: ' + response.mensaje);
            }
        },
        error: function() {
            alert('Error al aprobar la cita.');
        }
});

    });
</script>