Taller/Controllers/CarrosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;
using Taller.Models;
using Taller.Models.Services;
using Taller.Permisos;

namespace Taller.Controllers
{
    [ValidarPermisos]
    public class CarrosController : Controller
    {

        private TallerEntities db = new TallerEntities();
        private CarrosService carrosService = new CarrosService();

        // GET: Carros
        public ActionResult Index()
        {
            Usuario usuario = Session["usuario"] as Usuario;

            if (usuario != null && usuario.EsAdmin == 1)
            {
                return RedirectToAction("Index", "Home");

            }
            List<CarrosClientes> lista = db.GetCarrosClientes(usuario.IdUsuario).ToList();

            return View(db.GetCarrosClientes(usuario.IdUsuario).ToList());
        }

        // GET: Carros/Create
        public ActionResult Create()
        {
            return View();
        }
        // GET : Carros/Edit/5
        public ActionResult Edit(int? id)
        {
            Usuario usuarioSesion = Session["usuario"] as Usuario;

            if (usuarioSesion != null && usuarioSesion.EsAdmin == 1)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            CarrosClientes carro = db.CarrosClientes.Find(id);

            
            if(carro.IdCliente != usuarioSesion.IdUsuario)
            {
                return RedirectToAction("Index");
            }
            if (carro == null)
            {
                return HttpNotFound();
            }
           
            return View(carro);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCarroCliente,IdCliente,Modelo, Marca, Anio, Placas")] CarrosClientes carro)
        {
            if (ModelState.IsValid)
            {
                Usuario usuarioSesion = Session["usuario"] as Usuario;
                carro.IdCliente = usuarioSesion.IdUsuario ?? 0;

            }

            GeneralModel resultado = carrosService.RegistrarCarro(carro);


            if (resultado.Exitoso == 1)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["Mensaje"] = resultado.Mensaje;
                return View();
            }


        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCarroCliente, IdCliente, Modelo, Marca, Anio, Placas")] CarrosClientes carro)
        {

            if (ModelState.IsValid)
            {
                Usuario usuarioSesion = Session["usuario"] as Usuario;
                carro.IdCliente = usuarioSesion.IdUsuario ?? 0;

            }
            GeneralModel resultado = carrosService.RegistrarCarro(carro);


            if (resultado.Exitoso == 1)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["Mensaje"] = resultado.Mensaje;
                return View();
            }
        }


        // GET: Carros/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarrosClientes carro = db.CarrosClientes.Find(id);
            if (carro == null)
            {
                return HttpNotFound();
            }
            return View(carro);
        }

        // POST: Carros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GeneralModel resultado = carrosService.EliminarCarro(id);


            if (resultado.Exitoso == 1)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["Mensaje"] = resultado.Mensaje;
                return View();
            }
        }

    }
}

Taller/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Taller</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/css/Personalizaciones.css" rel="stylesheet" />
</head>

<body>
    @{
        Taller.Models.Usuario usuario = Session["Usuario"] as Taller.Models.Usuario;
    }
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Taller", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                    @if (usuario != null && usuario.EsAdmin == 1) //Menú exclusivo para administradores
                    {
                        <li>@Html.ActionLink("Usuarios", "Index", "Usuarios", new { area = "" }, new { @class = "nav-link" })</li>
                    }

                    @if (usuario != null && usuario.EsAdmin != 1) //Menú exclusivo para clientes
                    {
                        <li>@Html.ActionLink("Mis Carros", "Index", "Carros", new { id = 5 }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Mis Datos", "Edit", "Usuarios", new { id = 5 }, new { @class = "nav-link" })</li>
                    }
                    <li>@Html.ActionLink("Citas", "Index", "Citas", new { id = 5 }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Salir", "CerrarSesion", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Taller Claudia Loya</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>